name       : perl-test-mockrandom
version    : 1.01
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Test-MockRandom-1.01.tar.gz : 2614930d84fc5deac39afbc1ee86ccd39b221507f27d4ee493ca26e5c921cce0
license    : Apache-2.0
component  : programming.perl
summary    : Test::MockRandom - Replaces random number generation with non-random number generation
description: |
    Test::MockRandom - Replaces random number generation with non-random number generation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
